language: generic

git:
  depth: false

services:
  - docker

before_install:
  - cp .env.dist .env

install:
  - docker-compose up -d --build
  - docker exec -it mirrors_php_1 composer install
  - docker exec -it mirrors_php_1 vendor/bin/phinx migrate
  - docker exec -it -w=/code/tests mirrors_tests_1 composer install

script:
  - docker exec -it mirrors_tests_1 tests/vendor/bin/behat --config=behat/behat.yml
  - docker exec -it mirrors_tests_1 tests/vendor/bin/phpcs /code

after_script:
  - docker-compose stop
  - docker-compose rm -f

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
