language: php
php:
  - '7.0'

git:
  depth: false

services:
  - docker

sudo: required

env:
  - DOCKER_COMPOSE_VERSION=1.24

before_install:
  - cp .env.dist .env

install:
  - docker-compose up -d --build
  - docker exec -it mirrors_php_1 composer install
  - docker exec -it mirrors_php_1 vendor/bin/phinx migrate
  - docker exec -it mirrors_tests_1 composer install

script:
  - docker exec -it mirrors_tests_1 vendor/bin/behat --config=behat/behat.yml

after_script:
  - docker-compose stop
  - docker-compose rm -f
