language: generic

git:
  depth: false

services:
  - docker

cache:
  directories:
    - src/vendor
    - tests/vendor

before_install:
  - cp .env.dist .env

install:
  - docker-compose up -d --build
  - while sudo lsof -Pi :${DATABASE_PORT_EXTERNAL} -sTCP:LISTEN -t; do sleep 1; done #wait database
  - docker exec -it mirrors_php_1 composer install
  - docker exec -it mirrors_php_1 vendor/bin/phinx migrate
  - docker exec -it mirrors_tests_1 bash -c 'cd /code/tests; composer install;'

script:
  - docker exec -it mirrors_tests_1 tests/vendor/bin/behat --config=tests/behat/behat.yml
  - docker exec -it mirrors_tests_1 tests/vendor/bin/phpcs /code

after_script:
  - docker-compose stop
  - docker-compose rm -f

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
