version: '3'
services:
  postgresql:
    image: postgres:11-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_USER=$DATABASE_USERNAME
    ports:
      - $DATABASE_PORT_EXTERNAL:5432

  web:
    image: jonkofee/nginx
    working_dir: /code
    ports:
      - $NGINX_PORT_EXTERNAL:80
      - 80
    volumes:
      - ./docker/nginx/conf:/etc/nginx/conf.d
    links:
      - php
      - websocket
    environment:
      - DOMAIN=$DOMAIN
    networks:
      default:
        aliases:
          - api.$DOMAIN
          - static.$DOMAIN
          - other.$DOMAIN

  php:
    build: ./docker/php
    working_dir: /code
    volumes:
      - ./src:/code
    links:
      - postgresql
      - websocket
    ports:
      - 9000
    environment:
      - DATABASE_HOST=$DATABASE_HOST
      - DATABASE_USERNAME=$DATABASE_USERNAME
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - DATABASE_NAME=$DATABASE_NAME
      - DATABASE_PORT=$DATABASE_PORT_INTERNAL
      - JWT_KEY=$JWT_KEY

  websocket:
    build: ./docker/websocket
    working_dir: /code
    volumes:
      - ./src:/code
    ports:
      - $WEBSOCKET_PORT_EXTERNAL:8000
      - 1337
    environment:
      - JWT_KEY=$JWT_KEY

  tests:
    build: ./docker/tests
    working_dir: /code
    tty: true
    volumes:
      - ./:/code
    environment:
      - DATABASE_HOST=$DATABASE_HOST
      - DATABASE_USERNAME=$DATABASE_USERNAME
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - DATABASE_NAME=$DATABASE_NAME
      - DATABASE_PORT=$DATABASE_PORT_INTERNAL
      - JWT_KEY=$JWT_KEY
      - DOMAIN=$DOMAIN
