version: '3'
services:
  postgresql:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: devpass
      POSTGRES_USER: mirrors
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data

  web:
    image: nginx:latest
    ports:
      - ${NGINX_SERVER_PORT}:80
    volumes:
      - ./:/code
      - ./docker/nginx:/etc/nginx/conf.d
    links:
      - php
      - websocket

  php:
    build: ./docker/php
    working_dir: /code
    volumes:
      - ./:/code
    links:
      - postgresql
      - websocket
    ports:
      - 9000

  websocket:
    build: ./docker/websocket
    working_dir: /code
    volumes:
      - ./:/code
    ports:
      - ${WEBSOCKET_SERVER_PORT}:8000
      - 1337