name: Linter

on:
  push:
    paths-ignore:
    - 'docs/**'
  pull_request:
    branches: master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup env variables
        run: cp .env.dist .env

      - name: Run
        run: docker-compose up -d --build

      - name: Install dependencies
        run: docker exec -it mirrors_tests_1 bash -c 'cd /code/tests; composer install;'

      - name: Test
        run: docker exec -it mirrors_tests_1 tests/vendor/bin/phpcs /code
